"use strict";(self.webpackChunkheyaqing=self.webpackChunkheyaqing||[]).push([[433],{16894:function(X,T,i){i.r(T);var C=i(67294),g=i(85893),w=function(){var D=(0,C.useRef)(null);return(0,C.useEffect)(function(){var d=D.current,t=d==null?void 0:d.getContext("experimental-webgl");if(t){var I=function r(){rotateX(_),rotateY(_),rotateZ(_),t.uniformMatrix4fv(P,!1,new Float32Array(n)),t.clearColor(.5,.5,.5,1),t.clear(t.COLOR_BUFFER_BIT),t.drawArrays(t.LINE_STRIP,0,f.length/3),requestAnimationFrame(r)},U=`precision highp float;
      attribute vec3 position;
      uniform mat4 mat;
      varying vec4 color;
      void main(){
        gl_Position=mat*vec4(position,1.0);
     
        color=vec4(gl_Position.x,gl_Position.y,gl_Position.z,0.8);}
      `,B=`
      #ifdef GL_ES
          precision mediump float;
      #endif
          varying vec4 color;
          void main(){
              gl_FragColor=color;
          }
      `,s=t.createShader(t.VERTEX_SHADER),a=t.createShader(t.FRAGMENT_SHADER),l=t.createProgram();t.shaderSource(s,U),t.shaderSource(a,B),t.compileShader(s),t.compileShader(a),t.attachShader(l,s),t.attachShader(l,a),t.linkProgram(l),t.useProgram(l);var c=function(h,E,N,S,x){var u=new Array,j=-S;function z(W,p,K){for(var G=0,A=360/W,F=new Array,$=0;$<W;$++)F.push(Math.sin(Math.PI/180*G)*K,Math.cos(Math.PI/180*G)*K,p),G+=A;return F}for(var y=360/x,O=0,j=S,J=0,Q=y,V=0;V<x/2;V++){if(V>=x/4)var Y=Math.sin(Math.PI/180*O)*-S;else var Y=Math.sin(Math.PI/180*O)*-S;console.log(Y),O+=y;var o=z(x,Y,j);V>=x/4?Y=Math.sin(Math.PI/180*O)*-S:Y=-Math.sin(Math.PI/180*O)*-S,j=Math.sqrt(S*S-S*Math.sin(Math.PI/180*O)*S*Math.sin(Math.PI/180*O));for(var v=z(x,Y,j),e=0;e<o.length;e+=3)e==0?(u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(o[o.length-3],o[o.length-2],o[o.length-1]),u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(v[e+3],v[e+4],v[e+5])):e==o.length-3?(u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(o[e-3],o[e-2],o[e-1]),u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(v[0],v[1],v[2])):(u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(o[e-3],o[e-2],o[e-1]),u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(v[e+3],v[e+4],v[e+5]))}return u},f=c(0,0,0,.5,180),R=t.getAttribLocation(l,"position"),P=t.getUniformLocation(l,"mat");console.log(t.getShaderInfoLog(s));var n=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];console.log(t.getShaderInfoLog(a)),i.g.rotateX=function(r){var h=Math.cos(Math.PI/180*r),E=Math.sin(Math.PI/180*r),N=n[1],S=n[5],x=n[9];n[1]=h*n[1]-E*n[2],n[5]=h*n[5]-E*n[6],n[9]=h*n[9]-E*n[10],n[2]=E*N+h*n[2],n[6]=E*S+h*n[6],n[10]=E*x+h*n[10]},i.g.rotateY=function(r){var h=Math.cos(Math.PI/180*r),E=Math.sin(Math.PI/180*r),N=n[0],S=n[8],x=n[4];n[0]=h*n[0]+E*n[2],n[4]=h*n[4]+E*n[6],n[8]=h*n[8]+E*n[10],n[2]=h*n[2]-E*N,n[6]=h*n[6]-E*x,n[10]=h*n[10]-E*S},i.g.rotateZ=function(r){var h=Math.cos(Math.PI/180*r),E=Math.sin(Math.PI/180*r),N=n[0],S=n[4],x=n[8];n[0]=h*n[0]-E*n[1],n[4]=h*n[4]-E*n[5],n[8]=h*n[8]-E*n[9],n[1]=E*N+h*n[1],n[5]=E*S+h*n[5],n[9]=E*x+h*n[9]},i.g.moveX=function(r){n[0]=n[0]+r*n[3],n[4]=n[4]+r*n[7],n[8]=n[8]+r*n[11],n[12]=n[12]+r*n[15]},i.g.moveY=function(r){n[1]=r*n[3]+n[1],n[5]=r*n[7]+n[5],n[9]=r*n[11]+n[9],n[13]=r*n[15]+n[13]},i.g.moveZ=function(r){n[2]=r*n[3]+n[2],n[6]=r*n[7]+n[6],n[10]=r*n[11]+n[10],n[14]=r*n[15]+n[14]},i.g.scaleFun=function(r){n[0]=r*n[0],n[4]=r*n[4],n[8]=r*n[8],n[12]=r*n[12],n[1]=r*n[1],n[5]=r*n[5],n[9]=r*n[9],n[13]=r*n[13],n[2]=r*n[2],n[6]=r*n[6],n[10]=r*n[10],n[14]=r*n[14]};var L=t.createBuffer();t.bindBuffer(t.ARRAY_BUFFER,L),t.bufferData(t.ARRAY_BUFFER,new Float32Array(f),t.STATIC_DRAW),t.vertexAttribPointer(R,3,t.FLOAT,!1,0,0),t.enableVertexAttribArray(R);var b=.05,_=.5;I()}},[]),(0,g.jsx)("canvas",{ref:D,width:"200",height:"200"})};T.default=w},27246:function(X,T,i){i.r(T);var C=i(67294),g=i(85893),w=`attribute vec4 a_Position;
void main(){
  gl_Position =  a_Position;
}
`,H=`precision mediump float;
uniform vec4 u_FragColor;
void main() {
  gl_FragColor = u_FragColor;
}
`,D=function(){var t=(0,C.useRef)(null);function I(s,a,l,c,f){var R,P,n,L;return R=s*Math.pow(1-f,3),P=3*a*f*Math.pow(1-f,2),n=3*l*Math.pow(f,2)*(1-f),L=c*Math.pow(f,3),R+P+n+L}function U(s,a,l,c,f,R){return{x:I(s.x,a.x,l.x,c.x,f*R),y:I(s.y,a.y,l.y,c.y,f*R),z:I(s.z,a.z,l.z,c.z,f*R)}}function B(s,a,l,c,f,R){for(var P=f||100,n=R||1,L=n/(P-1),b=[],_=0;_<P;_++){var r=U(s,a,l,c,_,L);b.push(r.x),b.push(r.y),b.push(r.z)}return b}return(0,C.useEffect)(function(){var s=t.current,a=s==null?void 0:s.getContext("webgl");if(a){var l=a.createShader(a.VERTEX_SHADER),c=a.createShader(a.FRAGMENT_SHADER);a.shaderSource(l,w),a.shaderSource(c,H),a.compileShader(l);var f=a.getShaderParameter(l,a.COMPILE_STATUS);if(!f)throw new Error("compile Shader is failed");a.compileShader(c);var R=a.getShaderParameter(c,a.COMPILE_STATUS);if(!R)throw new Error("compile Shader is failed");var P=a.createProgram();a.attachShader(P,l),a.attachShader(P,c),a.linkProgram(P);var n=a.getProgramParameter(P,a.LINK_STATUS);if(!n)throw new Error("link Shader is failed");a.useProgram(P);var L=a.getAttribLocation(P,"a_Position"),b=a.getUniformLocation(P,"u_FragColor");a.uniform4fv(b,[0,1,1,1]);var _=B({x:-.7,y:0,z:0},{x:-.25,y:.5,z:0},{x:.25,y:.5,z:0},{x:.7,y:0,z:0},20,1),r=new Float32Array(_),h=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,h),a.bufferData(a.ARRAY_BUFFER,r,a.STATIC_DRAW),a.vertexAttribPointer(L,3,a.FLOAT,!1,0,0),a.enableVertexAttribArray(L),a.clearColor(0,0,0,1),a.clear(a.COLOR_BUFFER_BIT),a.drawArrays(a.LINE_STRIP,0,_.length/3)}},[]),(0,g.jsx)("canvas",{ref:t,width:"300",height:"200"})};T.default=D},38952:function(X,T,i){i.r(T);var C=i(67294),g=i(85893),w=function(){var D=(0,C.useRef)(null);return(0,C.useEffect)(function(){var d=D.current,t=d==null?void 0:d.getContext("webgl");if(t){var I=function(u,z,y,O,j,J,Q,V,Y){var o=function(A){var F=Math.sqrt(A[0]*A[0]+A[1]*A[1]+A[2]*A[2]);return[A[0]/F,A[1]/F,A[2]/F]},v=function(A,F){return[A[0]-F[0],A[1]-F[1],A[2]-F[2]]},e=function(A,F){return[A[1]*F[2]-A[2]*F[1],A[2]*F[0]-A[0]*F[2],A[0]*F[1]-A[1]*F[0]]},W=o(v([u,z,y],[O,j,J])),p=o(e([Q,V,Y],W)),K=o(e(W,p));return new Float32Array([p[0],K[0],W[0],0,p[1],K[1],W[1],0,p[2],K[2],W[2],0,-(p[0]*u+p[1]*z+p[2]*y),-(K[0]*u+K[1]*z+K[2]*y),-(W[0]*u+W[1]*z+W[2]*y),1])},U=function(u){return Math.PI*u/180},B=function(u,z,y,O){u=U(u);var j=1/Math.tan(u/2),J=1/(y-O);return new Float32Array([j/z,0,0,0,0,j,0,0,0,0,(O+y)*J,-1,0,0,2*O*y*J,0])},s=`
        attribute vec4 a_Position;
        attribute vec4 a_Color;
        uniform mat4 u_ViewMatrix;  // \u89C6\u56FE\u77E9\u9635
        uniform mat4 u_ProjMatrix; // \u6B63\u5C04\u6295\u5F71\u77E9\u9635
        mat4 u_MvpMatrix = u_ProjMatrix * u_ViewMatrix;
        varying vec4 v_Color;
        void main() {
        gl_Position = u_MvpMatrix * a_Position;
        v_Color = a_Color;
        }
        `,a=`
        precision highp float;
        varying vec4 v_Color;
        void main() {
          gl_FragColor = v_Color;
        }
        `,l=t.createShader(t.VERTEX_SHADER);t.shaderSource(l,s),t.compileShader(l);var c=t.createShader(t.FRAGMENT_SHADER);t.shaderSource(c,a),t.compileShader(c);var f=t.createProgram();t.attachShader(f,l),t.attachShader(f,c),t.linkProgram(f),t.useProgram(f),t.program=f;var R=new Float32Array([1,1,1,1,1,1,-1,1,1,1,0,1,-1,-1,1,1,0,0,1,-1,1,1,1,0,1,-1,-1,0,1,0,1,1,-1,0,1,1,-1,1,-1,0,0,1,-1,-1,-1,0,0,0]),P=new Uint8Array([0,1,2,0,2,3,0,3,4,0,4,5,0,5,6,0,6,1,1,6,7,1,7,2,7,4,3,7,3,2,4,7,6,4,6,5]),n=R.BYTES_PER_ELEMENT,L=t.createBuffer(),b=t.createBuffer();t.bindBuffer(t.ARRAY_BUFFER,L),t.bufferData(t.ARRAY_BUFFER,R,t.STATIC_DRAW),t.bindBuffer(t.ELEMENT_ARRAY_BUFFER,b),t.bufferData(t.ELEMENT_ARRAY_BUFFER,P,t.STATIC_DRAW);var _=t.getAttribLocation(t.program,"a_Position"),r=t.getAttribLocation(t.program,"a_Color"),h=t.getUniformLocation(t.program,"u_ViewMatrix"),E=I(3,4,8,0,0,0,0,1,0);t.uniformMatrix4fv(h,!1,E);var N=t.getUniformLocation(t.program,"u_ProjMatrix"),S=B(30,d.width/d.height,1,100);t.uniformMatrix4fv(N,!1,S),t.vertexAttribPointer(_,3,t.FLOAT,!1,n*6,0),t.enableVertexAttribArray(_),t.vertexAttribPointer(r,3,t.FLOAT,!1,n*6,n*3),t.enableVertexAttribArray(r),t.clearColor(0,0,0,1),t.enable(t.DEPTH_TEST),t.clear(t.COLOR_BUFFER_BIT|t.DEPTH_BUFFER_BIT),t.drawElements(t.TRIANGLES,P.length,t.UNSIGNED_BYTE,0)}},[]),(0,g.jsx)("canvas",{ref:D,width:"200",height:"200"})};T.default=w},63296:function(X,T,i){i.r(T);var C=i(67294),g=i(85893),w=function(){var D=(0,C.useRef)(null);return(0,C.useEffect)(function(){var d=D.current,t=d==null?void 0:d.getContext("2d");t&&(t.beginPath(),t.moveTo(20,20),t.lineTo(200,20),t.lineWidth=1,t.strokeStyle="#CC0000",t.stroke())},[]),(0,g.jsx)("canvas",{ref:D,width:"100",height:"100"})};T.default=w},2795:function(X,T,i){i.r(T);var C=i(67294),g=i(85893),w=function(){var D=(0,C.useRef)(null);return(0,C.useEffect)(function(){var d=D.current,t=d==null?void 0:d.getContext("webgl");if(t){var I=`
        attribute vec4 a_Position;
        void main() {
          gl_Position = a_Position;
        }
      `,U=`
        void main() {
          gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0); // \u7EA2\u8272
        }
      `,B=t.createShader(t.VERTEX_SHADER),s=t.createShader(t.FRAGMENT_SHADER);t.shaderSource(B,I),t.shaderSource(s,U),t.compileShader(B),t.compileShader(s);var a=t.createProgram();t.attachShader(a,B),t.attachShader(a,s),t.linkProgram(a),t.useProgram(a);var l=new Float32Array([1,1,-1,1,1,-1,-1,-1]),c=t.createBuffer();t.bindBuffer(t.ARRAY_BUFFER,c),t.bufferData(t.ARRAY_BUFFER,l,t.STATIC_DRAW);var f=t.getAttribLocation(a,"a_Position");t.vertexAttribPointer(f,2,t.FLOAT,!1,0,0),t.enableVertexAttribArray(f),t.drawArrays(t.TRIANGLE_STRIP,0,4)}},[]),(0,g.jsx)("canvas",{ref:D,width:"100",height:"100"})};T.default=w},44091:function(X,T,i){i.r(T);var C=i(67294),g=i(99477),w=i(85893),H=function(){var d=(0,C.useRef)(null);return(0,C.useEffect)(function(){var t=d.current,I=10,U=10,B;function s(){I=t.clientWidth,U=t.clientHeight,B=new g.CP7({antialias:!0}),B.setSize(I,U),t.appendChild(B.domElement),B.setClearColor(16777215,1)}var a;function l(){a=new g.cPb(45,I/U,1,1e4),a.position.x=0,a.position.y=2,a.position.z=1,a.up.x=0,a.up.y=0,a.up.z=1,a.lookAt(new g.Pa4(0,0,0))}var c;function f(){c=new g.xsS}var R;function P(){var _=new g.DvJ(1,1,1),r=new g.YBo({color:16777215});R=new g.Kj0(_,r),c.add(R)}function n(){var _=new g.cek(16711680);_.position.set(1,1,-1);var r=new g.cek(65280);r.position.set(1,-1,1),c.add(_),c.add(r)}function L(){R.rotation.x+=.01,R.rotation.y+=.01,B.render(c,a),requestAnimationFrame(L)}function b(){s(),l(),f(),P(),n(),L()}b()},[]),(0,w.jsx)("div",{ref:d,style:{width:150,height:150}})};T.default=H}}]);
