"use strict";(self.webpackChunkheyaqing=self.webpackChunkheyaqing||[]).push([[433],{16894:function(X,S,i){i.r(S);var T=i(67294),g=i(85893),w=function(){var D=(0,T.useRef)(null);return(0,T.useEffect)(function(){var d=D.current,n=d==null?void 0:d.getContext("experimental-webgl");if(n){var I=function r(){rotateX(B),rotateY(B),rotateZ(B),n.uniformMatrix4fv(P,!1,new Float32Array(t)),n.clearColor(.5,.5,.5,1),n.clear(n.COLOR_BUFFER_BIT),n.drawArrays(n.LINE_STRIP,0,f.length/3),requestAnimationFrame(r)},U=`precision highp float;
      attribute vec3 position;
      uniform mat4 mat;
      varying vec4 color;
      void main(){
        gl_Position=mat*vec4(position,1.0);
     
        color=vec4(gl_Position.x,gl_Position.y,gl_Position.z,0.8);}
      `,F=`
      #ifdef GL_ES
          precision mediump float;
      #endif
          varying vec4 color;
          void main(){
              gl_FragColor=color;
          }
      `,s=n.createShader(n.VERTEX_SHADER),a=n.createShader(n.FRAGMENT_SHADER),c=n.createProgram();n.shaderSource(s,U),n.shaderSource(a,F),n.compileShader(s),n.compileShader(a),n.attachShader(c,s),n.attachShader(c,a),n.linkProgram(c),n.useProgram(c);var h=function(l,E,N,_,x){var u=new Array,j=-_;function z(W,p,K){for(var G=0,A=360/W,C=new Array,$=0;$<W;$++)C.push(Math.sin(Math.PI/180*G)*K,Math.cos(Math.PI/180*G)*K,p),G+=A;return C}for(var y=360/x,O=0,j=_,J=0,Q=y,V=0;V<x/2;V++){if(V>=x/4)var Y=Math.sin(Math.PI/180*O)*-_;else var Y=Math.sin(Math.PI/180*O)*-_;console.log(Y),O+=y;var o=z(x,Y,j);V>=x/4?Y=Math.sin(Math.PI/180*O)*-_:Y=-Math.sin(Math.PI/180*O)*-_,j=Math.sqrt(_*_-_*Math.sin(Math.PI/180*O)*_*Math.sin(Math.PI/180*O));for(var v=z(x,Y,j),e=0;e<o.length;e+=3)e==0?(u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(o[o.length-3],o[o.length-2],o[o.length-1]),u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(v[e+3],v[e+4],v[e+5])):e==o.length-3?(u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(o[e-3],o[e-2],o[e-1]),u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(v[0],v[1],v[2])):(u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(o[e-3],o[e-2],o[e-1]),u.push(o[e],o[e+1],o[e+2]),u.push(v[e],v[e+1],v[e+2]),u.push(v[e+3],v[e+4],v[e+5]))}return u},f=h(0,0,0,.5,180),R=n.getAttribLocation(c,"position"),P=n.getUniformLocation(c,"mat");console.log(n.getShaderInfoLog(s));var t=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];console.log(n.getShaderInfoLog(a)),i.g.rotateX=function(r){var l=Math.cos(Math.PI/180*r),E=Math.sin(Math.PI/180*r),N=t[1],_=t[5],x=t[9];t[1]=l*t[1]-E*t[2],t[5]=l*t[5]-E*t[6],t[9]=l*t[9]-E*t[10],t[2]=E*N+l*t[2],t[6]=E*_+l*t[6],t[10]=E*x+l*t[10]},i.g.rotateY=function(r){var l=Math.cos(Math.PI/180*r),E=Math.sin(Math.PI/180*r),N=t[0],_=t[8],x=t[4];t[0]=l*t[0]+E*t[2],t[4]=l*t[4]+E*t[6],t[8]=l*t[8]+E*t[10],t[2]=l*t[2]-E*N,t[6]=l*t[6]-E*x,t[10]=l*t[10]-E*_},i.g.rotateZ=function(r){var l=Math.cos(Math.PI/180*r),E=Math.sin(Math.PI/180*r),N=t[0],_=t[4],x=t[8];t[0]=l*t[0]-E*t[1],t[4]=l*t[4]-E*t[5],t[8]=l*t[8]-E*t[9],t[1]=E*N+l*t[1],t[5]=E*_+l*t[5],t[9]=E*x+l*t[9]},i.g.moveX=function(r){t[0]=t[0]+r*t[3],t[4]=t[4]+r*t[7],t[8]=t[8]+r*t[11],t[12]=t[12]+r*t[15]},i.g.moveY=function(r){t[1]=r*t[3]+t[1],t[5]=r*t[7]+t[5],t[9]=r*t[11]+t[9],t[13]=r*t[15]+t[13]},i.g.moveZ=function(r){t[2]=r*t[3]+t[2],t[6]=r*t[7]+t[6],t[10]=r*t[11]+t[10],t[14]=r*t[15]+t[14]},i.g.scaleFun=function(r){t[0]=r*t[0],t[4]=r*t[4],t[8]=r*t[8],t[12]=r*t[12],t[1]=r*t[1],t[5]=r*t[5],t[9]=r*t[9],t[13]=r*t[13],t[2]=r*t[2],t[6]=r*t[6],t[10]=r*t[10],t[14]=r*t[14]};var L=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,L),n.bufferData(n.ARRAY_BUFFER,new Float32Array(f),n.STATIC_DRAW),n.vertexAttribPointer(R,3,n.FLOAT,!1,0,0),n.enableVertexAttribArray(R);var b=.05,B=.5;I()}},[]),(0,g.jsx)("canvas",{ref:D,width:"200",height:"200"})};S.default=w},27246:function(X,S,i){i.r(S);var T=i(67294),g=i(85893),w=`attribute vec4 a_Position;
void main(){
  gl_Position =  a_Position;
}
`,H=`precision mediump float;
uniform vec4 u_FragColor;
void main() {
  gl_FragColor = u_FragColor;
}
`,D=function(){var n=(0,T.useRef)(null);function I(s,a,c,h,f){var R,P,t,L;return R=s*Math.pow(1-f,3),P=3*a*f*Math.pow(1-f,2),t=3*c*Math.pow(f,2)*(1-f),L=h*Math.pow(f,3),R+P+t+L}function U(s,a,c,h,f,R){return{x:I(s.x,a.x,c.x,h.x,f*R),y:I(s.y,a.y,c.y,h.y,f*R),z:I(s.z,a.z,c.z,h.z,f*R)}}function F(s,a,c,h,f,R){for(var P=f||100,t=R||1,L=t/(P-1),b=[],B=0;B<P;B++){var r=U(s,a,c,h,B,L);b.push(r.x),b.push(r.y),b.push(r.z)}return b}return(0,T.useEffect)(function(){var s=n.current,a=s==null?void 0:s.getContext("webgl");if(a){var c=a.createShader(a.VERTEX_SHADER),h=a.createShader(a.FRAGMENT_SHADER);a.shaderSource(c,w),a.shaderSource(h,H),a.compileShader(c);var f=a.getShaderParameter(c,a.COMPILE_STATUS);if(!f)throw new Error("compile Shader is failed");a.compileShader(h);var R=a.getShaderParameter(h,a.COMPILE_STATUS);if(!R)throw new Error("compile Shader is failed");var P=a.createProgram();a.attachShader(P,c),a.attachShader(P,h),a.linkProgram(P);var t=a.getProgramParameter(P,a.LINK_STATUS);if(!t)throw new Error("link Shader is failed");a.useProgram(P);var L=a.getAttribLocation(P,"a_Position"),b=a.getUniformLocation(P,"u_FragColor");a.uniform4fv(b,[0,1,1,1]);var B=F({x:-.7,y:0,z:0},{x:-.25,y:.5,z:0},{x:.25,y:.5,z:0},{x:.7,y:0,z:0},20,1),r=new Float32Array(B),l=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,l),a.bufferData(a.ARRAY_BUFFER,r,a.STATIC_DRAW),a.vertexAttribPointer(L,3,a.FLOAT,!1,0,0),a.enableVertexAttribArray(L),a.clearColor(0,0,0,1),a.clear(a.COLOR_BUFFER_BIT),a.drawArrays(a.LINE_STRIP,0,B.length/3)}},[]),(0,g.jsx)("canvas",{ref:n,width:"300",height:"200"})};S.default=D},38952:function(X,S,i){i.r(S);var T=i(67294),g=i(85893),w=function(){var D=(0,T.useRef)(null);return(0,T.useEffect)(function(){var d=D.current,n=d==null?void 0:d.getContext("webgl");if(n){var I=function(u,z,y,O,j,J,Q,V,Y){var o=function(A){var C=Math.sqrt(A[0]*A[0]+A[1]*A[1]+A[2]*A[2]);return[A[0]/C,A[1]/C,A[2]/C]},v=function(A,C){return[A[0]-C[0],A[1]-C[1],A[2]-C[2]]},e=function(A,C){return[A[1]*C[2]-A[2]*C[1],A[2]*C[0]-A[0]*C[2],A[0]*C[1]-A[1]*C[0]]},W=o(v([u,z,y],[O,j,J])),p=o(e([Q,V,Y],W)),K=o(e(W,p));return new Float32Array([p[0],K[0],W[0],0,p[1],K[1],W[1],0,p[2],K[2],W[2],0,-(p[0]*u+p[1]*z+p[2]*y),-(K[0]*u+K[1]*z+K[2]*y),-(W[0]*u+W[1]*z+W[2]*y),1])},U=function(u){return Math.PI*u/180},F=function(u,z,y,O){u=U(u);var j=1/Math.tan(u/2),J=1/(y-O);return new Float32Array([j/z,0,0,0,0,j,0,0,0,0,(O+y)*J,-1,0,0,2*O*y*J,0])},s=`
        attribute vec4 a_Position;
        attribute vec4 a_Color;
        uniform mat4 u_ViewMatrix;  // \u89C6\u56FE\u77E9\u9635
        uniform mat4 u_ProjMatrix; // \u6B63\u5C04\u6295\u5F71\u77E9\u9635
        mat4 u_MvpMatrix = u_ProjMatrix * u_ViewMatrix;
        varying vec4 v_Color;
        void main() {
        gl_Position = u_MvpMatrix * a_Position;
        v_Color = a_Color;
        }
        `,a=`
        precision highp float;
        varying vec4 v_Color;
        void main() {
          gl_FragColor = v_Color;
        }
        `,c=n.createShader(n.VERTEX_SHADER);n.shaderSource(c,s),n.compileShader(c);var h=n.createShader(n.FRAGMENT_SHADER);n.shaderSource(h,a),n.compileShader(h);var f=n.createProgram();n.attachShader(f,c),n.attachShader(f,h),n.linkProgram(f),n.useProgram(f),n.program=f;var R=new Float32Array([1,1,1,1,1,1,-1,1,1,1,0,1,-1,-1,1,1,0,0,1,-1,1,1,1,0,1,-1,-1,0,1,0,1,1,-1,0,1,1,-1,1,-1,0,0,1,-1,-1,-1,0,0,0]),P=new Uint8Array([0,1,2,0,2,3,0,3,4,0,4,5,0,5,6,0,6,1,1,6,7,1,7,2,7,4,3,7,3,2,4,7,6,4,6,5]),t=R.BYTES_PER_ELEMENT,L=n.createBuffer(),b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,L),n.bufferData(n.ARRAY_BUFFER,R,n.STATIC_DRAW),n.bindBuffer(n.ELEMENT_ARRAY_BUFFER,b),n.bufferData(n.ELEMENT_ARRAY_BUFFER,P,n.STATIC_DRAW);var B=n.getAttribLocation(n.program,"a_Position"),r=n.getAttribLocation(n.program,"a_Color"),l=n.getUniformLocation(n.program,"u_ViewMatrix"),E=I(3,4,8,0,0,0,0,1,0);n.uniformMatrix4fv(l,!1,E);var N=n.getUniformLocation(n.program,"u_ProjMatrix"),_=F(30,d.width/d.height,1,100);n.uniformMatrix4fv(N,!1,_),n.vertexAttribPointer(B,3,n.FLOAT,!1,t*6,0),n.enableVertexAttribArray(B),n.vertexAttribPointer(r,3,n.FLOAT,!1,t*6,t*3),n.enableVertexAttribArray(r),n.clearColor(0,0,0,1),n.enable(n.DEPTH_TEST),n.clear(n.COLOR_BUFFER_BIT|n.DEPTH_BUFFER_BIT),n.drawElements(n.TRIANGLES,P.length,n.UNSIGNED_BYTE,0)}},[]),(0,g.jsx)("canvas",{ref:D,width:"200",height:"200"})};S.default=w},63296:function(X,S,i){i.r(S);var T=i(67294),g=i(85893),w=function(){var D=(0,T.useRef)(null);return(0,T.useEffect)(function(){var d=D.current,n=d==null?void 0:d.getContext("2d");n&&(n.beginPath(),n.moveTo(20,20),n.lineTo(200,20),n.lineWidth=1,n.strokeStyle="#CC0000",n.stroke())},[]),(0,g.jsx)("canvas",{ref:D,width:"100",height:"100"})};S.default=w},2795:function(X,S,i){i.r(S);var T=i(67294),g=i(85893),w=function(){var D=(0,T.useRef)(null);return(0,T.useEffect)(function(){var d=D.current,n=d==null?void 0:d.getContext("webgl");if(n){var I=`
        attribute vec4 a_Position;
        void main() {
          gl_Position = a_Position;
        }
      `,U=`
        void main() {
          gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0); // \u7EA2\u8272
        }
      `,F=n.createShader(n.VERTEX_SHADER),s=n.createShader(n.FRAGMENT_SHADER);n.shaderSource(F,I),n.shaderSource(s,U),n.compileShader(F),n.compileShader(s);var a=n.createProgram();n.attachShader(a,F),n.attachShader(a,s),n.linkProgram(a),n.useProgram(a);var c=new Float32Array([1,1,-1,1,1,-1,-1,-1]),h=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,h),n.bufferData(n.ARRAY_BUFFER,c,n.STATIC_DRAW);var f=n.getAttribLocation(a,"a_Position");n.vertexAttribPointer(f,2,n.FLOAT,!1,0,0),n.enableVertexAttribArray(f),n.drawArrays(n.TRIANGLE_STRIP,0,4)}},[]),(0,g.jsx)("canvas",{ref:D,width:"100",height:"100"})};S.default=w},44091:function(X,S,i){i.r(S);var T=i(67294),g=i(99477),w=i(85893),H=function(){var d=(0,T.useRef)(null);return(0,T.useEffect)(function(){var n=d.current,I=10,U=10,F;function s(){I=n.clientWidth,U=n.clientHeight,F=new g.CP7({antialias:!0}),F.setSize(I,U),n.appendChild(F.domElement),F.setClearColor(16777215,1)}var a;function c(){a=new g.cPb(45,I/U,1,1e4),a.position.x=0,a.position.y=2,a.position.z=1,a.up.x=0,a.up.y=0,a.up.z=1,a.lookAt(new g.Pa4(0,0,0))}var h;function f(){h=new g.xsS}var R;function P(){var b=new g.DvJ(1,1,1),B=new g.YBo({color:16777215});R=new g.Kj0(b,B),h.add(R);var r=new g.cek(16711680);r.position.set(1,1,-1);var l=new g.cek(65280);l.position.set(1,-1,1),h.add(r),h.add(l)}function t(){R.rotation.x+=.01,R.rotation.y+=.01,F.render(h,a),requestAnimationFrame(t)}function L(){s(),c(),f(),P(),t()}L()},[]),(0,w.jsx)("div",{ref:d,style:{width:150,height:150}})};S.default=H}}]);
