name: Build and Deploy
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          persist-credentials: false

      - name: Install dependencies # 下载依赖 打包项目
        run: npm install
      
       - name: Build with dumi
        # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
        run: npm run build

      - name: Deploy # 将打包内容发布到 github page
        uses: peaceiris/actions-gh-pages@v3 # 使用别人写好的 actions
        with:  # 自定义环境变量
          # ACCESS_TOKEN: ${{ secrets.TEST_A }}
          branch: main
          folder: docs-dist
          repository-name: heyaqing497/heyaqing497.github.io # 这是我的 github page 仓库
